### PR TITLE
Bug Bash

### PR DESCRIPTION
**Pull request by legitmaxwu**
Changes:
- Fixed reordering tag categories (Previously dragging did nothing)
- Fixed filter drawer overflow handling (Previously, overflowed filter items were hidden)
- Made post-apply "Go to Homepage" button actually go to homepage (Previously, it might take you to your last visited program)
- Creating a program now requires entering a code
- Made mentor responses show more clearly (Previously, they were tiny scrollable divs)
- Made question descriptions show during the application stage

### CODE REVIEW

**Comment by nova-admin** [comment]
#### 📝Changed routes:


| [**/create**](https://risc-i3t4g3elo-novaforgood.vercel.app/create) | [**…\]/mentors/edit-profile**](https://risc-i3t4g3elo-novaforgood.vercel.app/program/[slug]/[profileRoute]/mentors/edit-profile) |
|:-:|:-:|
|<a href="https://risc-i3t4g3elo-novaforgood.vercel.app/create">Screenshot of /create</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/FeQKcaJJi8j1ug82TJ2n0J1hxqBBFRynpwfERml5Z5JDClXAO-Prx8720Pi0p_MwbMxEo1a1ctYDMfigS2MOQA.png">(view full size)</a> |<a href="https://risc-i3t4g3elo-novaforgood.vercel.app/program/[slug]/[profileRoute]/mentors/edit-profile">Screenshot of /program/[slug]/[profileRoute]/mentors/edit-profile</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/do9ZPwQ3R6tXTBP6brz1DwWqXeTT8zvRqT7JfRlyIjIsKzZi5C6RUEXytkYEIOotItiO3AeKG3_8sf_CoI28wg.png">(view full size)</a> |



| [**…\[profileRoute\]/mentors**](https://risc-i3t4g3elo-novaforgood.vercel.app/program/[slug]/[profileRoute]/mentors) | [**…profileRoute\]/settings**](https://risc-i3t4g3elo-novaforgood.vercel.app/program/[slug]/[profileRoute]/settings) |
|:-:|:-:|
|<a href="https://risc-i3t4g3elo-novaforgood.vercel.app/program/[slug]/[profileRoute]/mentors">Screenshot of /program/[slug]/[profileRoute]/mentors</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Af5W-mrXHNuVlM8XEB0n6mDJrGyphjyjMiWJ1k1R5xHGmguEXvYASlX9kOWIx0j5h9At3DlBEJH9wsoK9pwjzw.png">(view full size)</a> |<a href="https://risc-i3t4g3elo-novaforgood.vercel.app/program/[slug]/[profileRoute]/settings">Screenshot of /program/[slug]/[profileRoute]/settings</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/TNLMDDP715opDl6ShxAn3F6r44qOAQLV6jU4865Wkk5_9QNviB-f0bw8sGv0bFx-gSuzjyn3O8MNIi_TT-MQwQ.png">(view full size)</a> |



| [**/program/\[slug\]/apply**](https://risc-i3t4g3elo-novaforgood.vercel.app/program/[slug]/apply) |
|:-:|
|<a href="https://risc-i3t4g3elo-novaforgood.vercel.app/program/[slug]/apply">Screenshot of /program/[slug]/apply</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/VwXwmPLYm1wSTEOkrDkqpOtmEQXf8FbDFACALa2uRe1jAoqpUK6UohhVEtqr1gwAxF04T-TPPbittBOM5xDZCw.png">(view full size)</a> |







Commit 6ec096e9762d390f9653dede2311f4910cb6129b (https://risc-i3t4g3elo-novaforgood.vercel.app).

**Review by innopoop — COMMENTED** [review]
I'm not sure if this is because of an incorrect setup or not:

I dropped the database for my backend locally and switched onto Max/tag-categories => tested this branch on the frontend and I'm getting this error for edit mentor profile page: 
image

**Review by innopoop — APPROVED** [review]
I figured out the problem so u can ignore my last comment. As of rn, admins can put the same name twice but I don't think that serves a problem practically 
image

**Comment by innopoop** [comment]
I also wanted to note- do we want to have tags in the profile show up in the same order as the categories they appear in the admin side (based off of category)? Another TODO would be to change the display of the tags in profile to show which category they're apart of (see picture)
image

**Comment by legitmaxwu** [comment]
> I also wanted to note- do we want to have tags in the profile show up in the same order as the categories they appear in the admin side (based off of category)? Another TODO would be to change the display of the tags in profile to show which category they're apart of (see picture). There are two categories of tags- one for 1, 4 and another for 7,10, but both tags show up side by side with no tag category displayed
> image

Added a P2 task for this--good catch!

**Comment by legitmaxwu** [comment]
> I figured out the problem so u can ignore my last comment. As of rn, admins can put the same name twice but I don't think that serves a problem practically
> image

I think this is okay to allow for now.

**Pull request merged**
