### PR TITLE
Availabilities Revamp

### PR DESCRIPTION
**Pull request by legitmaxwu**
I'll come back and leave more detailed notes later

### CODE REVIEW

**Review by innopoop — CHANGES_REQUESTED** [review]
Visually:
1. Overflow not accounted for  
image
2. Is this okay with us visually / same day overrides are stackable
image


Functionally: 
1. meetings before the current time on the current day are still allowed to be scheduled
image
2. just for documenting the error you're working on rn: days over 31 don't have interactable availabilities when booking a chat
image

**Comment by legitmaxwu** [comment]
Thanks for the feedback!

Visual:
1. Profile images are messed across across the app--let's fix them all in another PR.
2. Let's leave this for another PR as well, along with checking for existing accepted chat requests.

Functional:
1. Sadge
2. Will work on this!
3. Let's figure this out later, not sure how far ahead we should let people book (I agree it should not be infinite)

**Comment by nova-admin** [comment]
#### 📝Changed routes:


| [**…/\[slug\]/availabilities**](https://risc-370ngraux-novaforgood.vercel.app/program/[slug]/availabilities) | [**/program/\[slug\]**](https://risc-370ngraux-novaforgood.vercel.app/program/[slug]) |
|:-:|:-:|
|<a href="https://risc-370ngraux-novaforgood.vercel.app/program/[slug]/availabilities">Screenshot of /program/[slug]/availabilities</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/N5gdaUQk-Hvts5pKTyN2dPy_rQZzqEO2-ZYocCKoell_75W427-Ipo2aCKP_UagzN6xRlFPmoL8Lt_T-hgt8vg.png">(view full size)</a> |<a href="https://risc-370ngraux-novaforgood.vercel.app/program/[slug]">Screenshot of /program/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/-VnmOT8kHAvZ3AqD_p_lK4Gsvg4wFRZSAnWAtdVoKKoLusKaGr09QAn8ELAFMPuninjxjvtgZNJZTKn7-qABlA.png">(view full size)</a> |



| [**/program/\[slug\]/mentees**](https://risc-370ngraux-novaforgood.vercel.app/program/[slug]/mentees) | [**/program/\[slug\]/mentors**](https://risc-370ngraux-novaforgood.vercel.app/program/[slug]/mentors) |
|:-:|:-:|
|<a href="https://risc-370ngraux-novaforgood.vercel.app/program/[slug]/mentees">Screenshot of /program/[slug]/mentees</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Hifw5jYCEEMbID2JloQD8wn3I5jqKoATvIK512hD3n9cO8YJztSR6l8X7m_lciq5nqkU2CHDzSnL8b5ghxMz6w.png">(view full size)</a> |<a href="https://risc-370ngraux-novaforgood.vercel.app/program/[slug]/mentors">Screenshot of /program/[slug]/mentors</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/jv3tCYgSvFG3kkze2ZLz09zNH_TIvBej-nrC264ml4BUVz3nMrGPNSPPqlxqrYYFNh-27MJF-NzT-G-h6WP_qw.png">(view full size)</a> |



| [**/signup**](https://risc-370ngraux-novaforgood.vercel.app/signup) |
|:-:|
|<a href="https://risc-370ngraux-novaforgood.vercel.app/signup">Screenshot of /signup</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Wze0Yba3ytVSUYIOCk-pEEnMJH5A424_kDH5yQ4Od7FhqxzAq5AS8K8Y8a44jaRJCL8lxFZu5jpKdGNTaHBIEw.png">(view full size)</a> |





1 deleted route:
- **/test/testcalendar**

Commit a1e6097f7ee410767a92b08ac9fbf73c37ca86f0 (https://risc-370ngraux-novaforgood.vercel.app).

**Review by innopoop — APPROVED** [review]
Only one question: Do we get rid of existing overrides once the date has passed?
image

Rest is LGTM for the time being!

**Comment by legitmaxwu** [comment]
Not currently--we can address this in a later PR.

**Pull request merged**
