### PR TITLE
Login page styling

### PR DESCRIPTION
**Pull request by legitmaxwu**
Addresses #33 

* Added text logo to top left corner
* Extracted TitledInput into components folder

### CODE REVIEW

**Comment by nova-admin** [comment]
#### 📝Changed routes:


| [**/login**](https://risc-dn0my6q9q-novaforgood.vercel.app/login) | [**/signup**](https://risc-dn0my6q9q-novaforgood.vercel.app/signup) |
|:-:|:-:|
|<a href="https://risc-dn0my6q9q-novaforgood.vercel.app/login">Screenshot of /login</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/UGn_mnuVGlXVruB0OPp6lwzjmYz3_tj6ng1AJNH4uTyAVmp4BN7WMsvI8FTmR0jwzfmBjRJLLwpCWoCSF8coDg.png">(view full size)</a> |<a href="https://risc-dn0my6q9q-novaforgood.vercel.app/signup">Screenshot of /signup</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/LRzQsQlxvLR-zXpFqQitFdRzX6IvkRAHBQBPWaxNre-m2GFawG76AaVRyLKFxFla6c7VO5lojMzcpRa6dwVkgA.png">(view full size)</a> |







Commit 3196f49c1cf3434f497de14383b6219d78f2db05 (https://risc-dn0my6q9q-novaforgood.vercel.app).

**Review by kevinl120 — APPROVED** [review]
LGTM

One question--do we want to move `BlobCircle` into the components folder at some point? Seems like it's used in a lot of places besides signup and login.

**Comment by legitmaxwu** [comment]
> One question--do we want to move `BlobCircle` into the components folder at some point? Seems like it's used in a lot of places besides signup and login.

Yeah good idea, let's do it once those pages are implemented

**Comment by innopoop** [comment]
image

This isn't a note on the actual code, just that in the future if we want people to be able to test using branches, we'll have to authorize the branches to access the firebase

**Comment by innopoop** [comment]
LGTM

**Review by innopoop — APPROVED** [review]

**Comment by legitmaxwu** [comment]
> This isn't a note on the actual code, just that in the future if we want people to be able to test using branches, we'll have to authorize the branches to access the firebase

Good point. I looked into it and Firebase doesn't allow for wildcard domains, and I'm not sure if it's a good idea to just authorize vercel.app because then any app under the domain could access it. @kevinl120 Thoughts?

**Pull request merged**
